In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

In [3]:
CHEMIN = "./"

In [4]:
data = pd.read_csv(CHEMIN + "daily_ozone_and_covariates.csv")
data.head()

   idSensor         day  maxTemp  minTemp  rainSum  windSpeed  maxOzone
0      5707  2018-01-01      6.4     -1.0      3.3       11.9      15.8
1      5707  2018-01-02     12.0     -0.6      0.0       15.5      71.2
2      5707  2018-01-03      7.8     -1.3      1.7       21.3      68.6
3      5707  2018-01-04     11.2      1.3      3.1       13.0      78.4
4      5707  2018-01-05      6.9     -0.5      0.4        9.4       3.9

In [8]:
data.shape

(125782, 7)

In [10]:
data["day"] = pd.to_datetime(data["day"])

In [12]:
data["week"] = data["day"].dt.to_period("W")

In [22]:
weekly_data = data.groupby(["idSensor", "week"]).agg({"maxTemp": ['max'], 
                                        "minTemp": ['min'], 
                                        "rainSum": ['sum'], 
                                        "windSpeed": ['max'],
                                       "maxOzone": ['max']}).reset_index()

In [32]:
weekly_data.columns = ["idSensor", "week", "maxTemp", "minTemp", "rainSum", "windSpeed", "maxOzone"]

In [34]:
weekly_data.head()

,idSensor,week,maxTemp,minTemp,rainSum,windSpeed,maxOzone
0,5707,2018-01-01/2018-01-07,12.0,-1.3,20.3,21.3,78.4
1,5707,2018-01-08/2018-01-14,11.7,-0.9,57.3,35.5,59.6
2,5707,2018-01-15/2018-01-21,13.5,-3.2,2.6,22.0,79.7
3,5707,2018-01-22/2018-01-28,10.2,-2.2,15.3,15.5,49.6
4,5707,2018-01-29/2018-02-04,10.0,-1.3,4.4,16.9,55.7

In [36]:
weekly_data.to_csv(CHEMIN + "weekly_ozone_and_covariates.csv", header=True, index=False)